config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
end

app/models/spree/promotion/actions/create_filtered_item_adjustments.rb
module Spree
  class Promotion
    module Actions
      class CreateFilteredItemAdjustments < PromotionAction
        include Spree::CalculatedAdjustments
        include Spree::AdjustmentSource

        has_many :promotion_action_taxons, class_name: 'Spree::PromotionActionTaxon', foreign_key: :promotion_action_id
        has_many :taxons, through: :promotion_action_taxons
        accepts_nested_attributes_for :promotion_action_taxons

        # Creates a filtered adjustment that only applies to specific items.
        # Items can be excluded from the discount by providing filtered Taxons.
        #
        # This allows forthe configuration of a promotion that is _earned_ at the
        # order level, but _applied_ at the line item level

        before_validation -> { self.calculator ||= Calculator::PercentOnLineItem.new }

        def perform(options = {})
          order     = options[:order]
          promotion = options[:promotion]

          create_unique_adjustments(order, order.line_items) do |line_item|
            !product_excluded?(line_item.product) && promotion.line_item_actionable?(order, line_item)
          end
        end

        def compute_amount(line_item)
          return 0 unless !product_excluded?(line_item.product) && promotion.line_item_actionable?(line_item.order, line_item)

          amounts = [line_item.amount, compute(line_item)]
          order   = line_item.order

          # Prevent negative order totals
          amounts << order.amount - order.adjustments.sum(:amount).abs if order.adjustments.any?

          amounts.min * -1
        end

        # Return true if the individual item is eligible for the discount
        def product_excluded?(product)
          taxons.each do |taxon|
            return true if product.taxons.include? taxon
          end

          return false
        end

      end
    end
  end
end

app/models/spree/promotion/rules/total_quantity.rb
# A rule to apply to an order's item quantity greater than (or greater than or equal to)
# a specific amount
module Spree
  class Promotion
    module Rules
      class TotalQuantity < PromotionRule
        preference :amount_min, :number, default: 0
        preference :operator_min, :string, default: '>'
        preference :amount_max, :number, default: 10
        preference :operator_max, :string, default: '<'

        OPERATORS_MIN = ['gt', 'gte']
        OPERATORS_MAX = ['lt','lte']

        def applicable?(promotable)
          promotable.is_a?(Spree::Order)
        end

        def eligible?(order, options = {})
          total_quantity = order.line_items.sum(&:quantity)

          lower_limit_condition = total_quantity.send(preferred_operator_min == 'gte' ? :>= : :>, preferred_amount_min.to_i)
          upper_limit_condition = total_quantity.send(preferred_operator_max == 'lte' ? :<= : :<, preferred_amount_max.to_i)

          eligibility_errors.add(:base, ineligible_message_max) unless upper_limit_condition
          eligibility_errors.add(:base, ineligible_message_min) unless lower_limit_condition

          eligibility_errors.empty?
        end

        private
        def formatted_amount_min
          Spree::Money.new(preferred_amount_min).to_s
        end

        def formatted_amount_max
          Spree::Money.new(preferred_amount_max).to_s
        end


        def ineligible_message_max
          if preferred_operator_max == 'gte'
            eligibility_error_message(:total_quantity_more_than_or_equal, amount: formatted_amount_max)
          else
            eligibility_error_message(:total_quantity_more_than, amount: formatted_amount_max)
          end
        end

        def ineligible_message_min
          if preferred_operator_min == 'gte'
            eligibility_error_message(:total_quantity_less_than, amount: formatted_amount_min)
          else
            eligibility_error_message(:total_quantity_less_than_or_equal, amount: formatted_amount_min)
          end
        end

      end
    end
  end
end

app/models/spree/promotion/rules/user_roles_includes.rb
module Spree
  class Promotion
    module Rules
      class UserRolesIncludes < PromotionRule
        preference :role_id, :number, default: nil

        def applicable?(promotable)
          promotable.is_a?(Spree::Order)
        end

        def eligible?(order, _options = {})
          if preferred_role_id.nil? || order.user.nil?
            return false
          end

          role = Spree::Role.find(preferred_role_id)

          unless order.user.spree_roles.include?(role)
            eligibility_errors.add(:base, eligibility_error_message(:no_user_specified))
          end

          return eligibility_errors.empty?
        end
      end
    end
  end
end

app/models/spree/promotion_action_taxon.rb
module Spree
  class PromotionActionTaxon < Spree::Base
    belongs_to :promotion_action, class_name: 'Spree::Promotion::Actions::CreateFilteredItemAdjustments'
    belongs_to :taxon, class_name: 'Spree::Taxon'

    validates :promotion_action, :taxon, presence: true
  end
end

app/views/spree/admin/promotions/actions/_create_filtered_item_adjustments.html.erb
<div class="panel-body">

  <div class="row">
    <div class="form-group col-xs-12 col-md-6 no-marginb">
      <% field_name = "#{param_prefix}[calculator_type]" %>
      <%= label_tag field_name, Spree.t(:calculator) %>
      <%= select_tag field_name,
                    options_from_collection_for_select(Spree::Promotion::Actions::CreateItemAdjustments.calculators, :to_s, :description, promotion_action.calculator.type),
                    class: 'type-select select2' %>
    </div>
    <% unless promotion_action.new_record? %>
      <div class="form-group col-xs-12 col-md-6 no-marginb settings">
        <% promotion_action.calculator.preferences.keys.map do |key| %>
          <% field_name = "#{param_prefix}[calculator_attributes][preferred_#{key}]" %>
          <%= label_tag field_name, Spree.t(key.to_s) %>
          <%= preference_field_tag(field_name,
                                   promotion_action.calculator.get_preference(key),
                                   type: promotion_action.calculator.preference_type(key)) %>
        <% end %>
        <%= hidden_field_tag "#{param_prefix}[calculator_attributes][id]", promotion_action.calculator.id %>
      </div>
    <% end %>
  </div>
  <% if promotion_action.calculator.respond_to?(:preferences) %>
    <div class="alert alert-info js-warning margint no-marginb">
      <%= Spree.t(:calculator_settings_warning) %>
    </div>
  <% end %>

  <div class="row no-marbinb"
    <div class="form_group col-xs-12 no-margin">
      <%= label_tag :taxon_ids, Spree.t(:excluded_taxons) %>

      <%= select_tag "#{param_prefix}[taxon_ids]", options_from_collection_for_select(Spree::Taxon.all, 'id', 'name', selected: promotion_action.taxon_ids),
          {
            multiple: true,
            id: 'promotion_action_taxon_ids',
            class: 'select2'
          }
      %>
    </div>
  </div>
</div>

app/views/spree/admin/promotions/rules/_total_quantity.html.erb
<div class="panel-body">
  <div class="row no-marginb">
    <div class="col-md-12">
      <%= label_tag  Spree.t("promotion_rule_types.total_quantity.label") %>
    </div>
    <div class="form-group col-md-6 no-marginb">
      <%= select_tag "#{param_prefix}[preferred_operator_min]",
                      options_for_select(Spree::Promotion::Rules::TotalQuantity::OPERATORS_MIN.map{|o| [Spree.t("promotion_rule_types.total_quantity.operators.#{o}"),o]}, promotion_rule.preferred_operator_min),
                      { class: 'select2 select_total_quantity marginb' }
      %>
      <%= select_tag "#{param_prefix}[preferred_operator_max]",
                      options_for_select(Spree::Promotion::Rules::TotalQuantity::OPERATORS_MAX.map{|o| [Spree.t("promotion_rule_types.total_quantity.operators.#{o}"),o]}, promotion_rule.preferred_operator_max),
                      { class: 'select2 select_total_quantity' }
      %>
    </div>
    <div class="form-group col-md-6 no-marginb">
      <%= text_field_tag "#{param_prefix}[preferred_amount_min]", promotion_rule.preferred_amount_min, class: 'form-control marginb' %>
      <%= text_field_tag "#{param_prefix}[preferred_amount_max]", promotion_rule.preferred_amount_max, class: 'form-control' %>
    </div>
  </div>
</div>

app/views/spree/admin/promotions/rules/_user_roles_includes.html.erb
<div class="panel-body">
  <div class="form-group roles_rule_role">
    <% @roles = Spree::Role.all %>
    <%= label_tag "#{param_prefix}_role_id_string", Spree.t('user_roles_includes_rule.choose_role') %>

    <%= select_tag "#{param_prefix}[preferred_role_id]",
                    options_for_select(@roles.map{|r| [r.name, r.id]}, promotion_rule.preferred_role_id),
                    { class: 'select2 select_total_quantity' }
    %>
  </div>
</div>